apiVersion: v1
kind: ConfigMap
metadata:
  name: poll0-config
  labels:
    app.kubernetes.io/name: poll0
data:
  INSTANCE_DOMAIN: "api.topia.io"
  INSTANCE_PROTOCOL: "https"
  INTERACTIVE_KEY: "t8YeuySKs8ETWIOLUA64"
  NODE_ENV: "production"
  PORT: "3000"
